import { createOctokit } from './octokit'
import { evaluate } from './evaluate'
import { hideOldComments, postComment } from './comment'
import { parseArgs, getToken, detectRepo, detectPR } from './cli-utils'

async function main(): Promise<void> {
  const args = parseArgs(process.argv)
  const token = getToken()
  const octokit = createOctokit(token) as any // compatible with Octokit type from @actions/github

  const repoFull = args.repo ?? detectRepo()
  const [owner, repo] = repoFull.split('/')
  if (!owner || !repo) {
    console.error(`Error: Invalid repo format "${repoFull}". Expected "owner/repo".`)
    process.exit(1)
  }

  const prNumber = args.pr ?? detectPR()

  console.error(`Evaluating readiness for PR #${prNumber} (${owner}/${repo})`)

  const result = await evaluate({ octokit, owner, repo, prNumber })

  // Print chart to stdout (clean for piping)
  console.log(result.chart)

  // Print summary to stderr
  console.error(`\nGates: branch=${result.branch.status} checks=${result.checks.status} threads=${result.threads.status}`)
  console.error(result.allPassed ? 'Result: READY' : 'Result: NOT READY')

  if (args.post) {
    const commentTag = 'ready-or-not-marker'
    const commentBody = `${result.chart}\n\n<sub>Generated by <a href="https://github.com/patrickclery/ready-or-not">ready-or-not</a> (CLI)</sub>\n\n<!-- ${commentTag} -->`
    const hidden = await hideOldComments(octokit, owner, repo, prNumber, commentTag)
    if (hidden > 0) console.error(`Hidden ${hidden} previous comment(s)`)
    await postComment(octokit, owner, repo, prNumber, commentBody)
    console.error('Posted readiness chart comment')
  }

  process.exit(result.allPassed ? 0 : 1)
}

main().catch((err) => {
  console.error(err instanceof Error ? err.message : String(err))
  process.exit(2)
})
