import * as core from '@actions/core'
import * as github from '@actions/github'
import { evaluate } from './evaluate'
import { hideOldComments, postComment, addReaction } from './comment'

async function run(): Promise<void> {
  const token = core.getInput('token', { required: true })
  const commentTag = core.getInput('comment-tag') || 'ready-or-not-marker'
  const octokit = github.getOctokit(token)
  const { owner, repo } = github.context.repo

  // Resolve PR number
  let prNumber = parseInt(core.getInput('pr-number'), 10)
  if (isNaN(prNumber)) {
    if (github.context.eventName === 'issue_comment') {
      prNumber = github.context.payload.issue?.number ?? 0
    } else if (github.context.eventName === 'pull_request') {
      prNumber = github.context.payload.pull_request?.number ?? 0
    }
  }

  if (!prNumber) {
    core.setFailed('Could not determine PR number. Provide pr-number input or use with issue_comment/pull_request events.')
    return
  }

  core.info(`Evaluating readiness for PR #${prNumber}`)

  const result = await evaluate({
    octokit,
    owner,
    repo,
    prNumber,
    selfCheckName: github.context.job,
  })

  core.info(`Gates: branch=${result.branch.status} checks=${result.checks.status} threads=${result.threads.status}`)

  const commentBody = `${result.chart}\n\n<sub>Generated by <a href="https://github.com/patrickclery/ready-or-not">ready-or-not</a></sub>\n\n<!-- ${commentTag} -->`

  // Hide old comments, post new one
  const hidden = await hideOldComments(octokit, owner, repo, prNumber, commentTag)
  if (hidden > 0) {
    core.info(`Hidden ${hidden} previous readiness comment(s)`)
  }

  await postComment(octokit, owner, repo, prNumber, commentBody)
  core.info('Posted readiness chart comment')

  // React to trigger comment if issue_comment event
  if (github.context.eventName === 'issue_comment') {
    const triggerCommentId = github.context.payload.comment?.id
    if (triggerCommentId) {
      await addReaction(octokit, owner, repo, triggerCommentId)
    }
  }
}

run().catch((error) => {
  core.setFailed(error instanceof Error ? error.message : String(error))
})
