import * as core from '@actions/core'
import * as github from '@actions/github'
import { evaluateBranch } from './gates/branch'
import { evaluateChecks } from './gates/checks'
import { evaluateThreads } from './gates/threads'
import { generateChart } from './chart'
import { hideOldComments, postComment, addReaction } from './comment'

async function run(): Promise<void> {
  const token = core.getInput('token', { required: true })
  const commentTag = core.getInput('comment-tag') || 'ready-or-not-marker'
  const octokit = github.getOctokit(token)
  const { owner, repo } = github.context.repo

  // Resolve PR number
  let prNumber = parseInt(core.getInput('pr-number'), 10)
  if (isNaN(prNumber)) {
    if (github.context.eventName === 'issue_comment') {
      prNumber = github.context.payload.issue?.number ?? 0
    } else if (github.context.eventName === 'pull_request') {
      prNumber = github.context.payload.pull_request?.number ?? 0
    }
  }

  if (!prNumber) {
    core.setFailed('Could not determine PR number. Provide pr-number input or use with issue_comment/pull_request events.')
    return
  }

  core.info(`Evaluating readiness for PR #${prNumber}`)

  // Fetch PR details
  const { data: pr } = await octokit.rest.pulls.get({ owner, repo, pull_number: prNumber })
  const headSha = pr.head.sha
  const baseRef = pr.base.ref
  const headRef = pr.head.ref

  // Evaluate all three gates in parallel
  const [compareData, checkRunsData, threadsData] = await Promise.all([
    octokit.rest.repos.compareCommits({
      owner,
      repo,
      base: baseRef,
      head: headRef,
    }),
    octokit.rest.checks.listForRef({
      owner,
      repo,
      ref: headSha,
      per_page: 100,
    }),
    octokit.graphql<{
      repository: {
        pullRequest: {
          reviewThreads: {
            nodes: Array<{ isResolved: boolean }>
          }
        }
      }
    }>(
      `query($owner: String!, $repo: String!, $pr: Int!) {
        repository(owner: $owner, name: $repo) {
          pullRequest(number: $pr) {
            reviewThreads(first: 100) {
              nodes { isResolved }
            }
          }
        }
      }`,
      { owner, repo, pr: prNumber }
    ),
  ])

  const branch = evaluateBranch({
    behind_by: compareData.data.behind_by,
    ahead_by: compareData.data.ahead_by,
  })

  // Filter out this action's own check run (it's always in_progress while we evaluate)
  const currentJob = github.context.job
  const filteredCheckRuns = checkRunsData.data.check_runs.filter(
    (cr) => cr.name !== currentJob
  )

  const checks = evaluateChecks(
    filteredCheckRuns.map((cr) => ({
      name: cr.name,
      conclusion: cr.conclusion,
      status: cr.status,
    }))
  )

  const threads = evaluateThreads(
    threadsData.repository.pullRequest.reviewThreads.nodes
  )

  core.info(`Gates: branch=${branch.status} checks=${checks.status} threads=${threads.status}`)

  // Generate chart
  const chartBody = generateChart({
    branch,
    checks,
    threads,
    prTitle: pr.title,
    headRef,
    baseRef,
    prNumber,
    prState: pr.state.toUpperCase(),
  })

  const commentBody = `${chartBody}\n\n<sub>Generated by <a href="https://github.com/patrickclery/ready-or-not">ready-or-not</a></sub>\n\n<!-- ${commentTag} -->`

  // Hide old comments, post new one
  const hidden = await hideOldComments(octokit, owner, repo, prNumber, commentTag)
  if (hidden > 0) {
    core.info(`Hidden ${hidden} previous readiness comment(s)`)
  }

  await postComment(octokit, owner, repo, prNumber, commentBody)
  core.info('Posted readiness chart comment')

  // React to trigger comment if issue_comment event
  if (github.context.eventName === 'issue_comment') {
    const triggerCommentId = github.context.payload.comment?.id
    if (triggerCommentId) {
      await addReaction(octokit, owner, repo, triggerCommentId)
    }
  }
}

run().catch((error) => {
  core.setFailed(error instanceof Error ? error.message : String(error))
})
